version: "3.3" 
services:
  goevent-organisation:
    image: unified-message:lastest
    restart: always
    #image: gofood/providerms:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "goevent-unified-message"
    ports:
      - "9194:9194"
    # command: |
    #   sh -c "
    #     node ace migration:run --force && node bin/server.js
    #   "
    networks:
      - goevent-ms-network
    logging:
      driver: loki
      options:
        loki-url: "http://173.249.48.147:3100/loki/api/v1/push"
   # depends_on:
     # - mysqldb 

networks:
  goevent-ms-network: 
    #name: zonoa-ms-network
    external: true