version: "3.3" 
services:
  goevent-organisation:
    image: unified-message:lastest
    restart: always
    #image: gofood/providerms:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "goevent-unified-message"
    ports:
      - "9193:9193"
    environment:
      - TZ=UTC
      - PORT=9194
      - HOST=0.0.0.0
      - APP_KEY=14eMwErjhxTU01FDm6mu66wQAT3D5g37
      - APP_NAME=Organization_Service_Documentation
      - LOG_LEVEL=info
      - NODE_ENV=production
      - DB_HOST=173.249.48.147
      - DB_PORT=5432
      - DB_USER=user02
      - DB_PASSWORD=2025userevent
      - DB_DATABASE=goevent_organization
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - EUREKA_APP_NAME=Organization-service
      - EUREKA_APP_IPAADDR=173.249.48.147
      - EUREKA_HOST=173.249.48.147
      - EUREKA_PORT=9192
      - MINIO_HOST=localhost
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secret
      - MINIO_USE_SSL=false
    # command: |
    #   sh -c "
    #     node ace migration:run --force && node bin/server.js
    #   "
    networks:
      - goevent-ms-network
    logging:
      driver: loki
      options:
        loki-url: "http://173.249.48.147:3100/loki/api/v1/push"
   # depends_on:
     # - mysqldb 

networks:
  goevent-ms-network: 
    #name: zonoa-ms-network
    external: true