openapi: "3.0.0"
info:
  title: "Unified Messaging Service"
  version: "0.0.0"
  description: "Unified Messaging Service"
components:
  responses:
    Forbidden:
      description: "Access token is missing or invalid"
    Accepted:
      description: "The request was accepted"
    Created:
      description: "The resource has been created"
    NotFound:
      description: "The resource has been created"
    NotAcceptable:
      description: "The resource has been created"
  securitySchemes:
    BearerAuth:
      type: "http"
      scheme: "bearer"
    BasicAuth:
      type: "http"
      scheme: "basic"
    ApiKeyAuth:
      type: "apiKey"
      in: "header"
      name: "X-API-Key"
  schemas:
    Any:
      description: "Any JSON object not defined as schema"
    PaginationMeta:
      type: "object"
      properties:
        total:
          type: "number"
          example: 100
          nullable: false
        page:
          type: "number"
          example: 2
          nullable: false
        perPage:
          type: "number"
          example: 10
          nullable: false
        currentPage:
          type: "number"
          example: 3
          nullable: false
        lastPage:
          type: "number"
          example: 10
          nullable: false
        firstPage:
          type: "number"
          example: 1
          nullable: false
        lastPageUrl:
          type: "string"
          example: "/?page=10"
          nullable: false
        firstPageUrl:
          type: "string"
          example: "/?page=1"
          nullable: false
        nextPageUrl:
          type: "string"
          example: "/?page=6"
          nullable: false
        previousPageUrl:
          type: "string"
          example: "/?page=5"
          nullable: false
paths:
  /mails/send-text:
    post:
      summary: "Send text mail (handle)"
      description: "Sned text mail\n\n _app/mail/controllers/send_text_mail_controller.ts_ - **handle**"
      operationId: "sendTextMail"
      parameters: []
      tags:
        - "MAILS"
      responses:
        201:
          description: "Created"
          content:
            application/json: {}
      security: []
  /mails/send-from-template:
    post:
      summary: "@summary (handle)"
      description: "@description\n\n _app/mail/controllers/send_from_template_mail_controller.ts_ - **handle**"
      operationId: "@operationId"
      parameters: []
      tags:
        - "MAILS"
      responses:
        201:
          description: "Created"
          content:
            application/json: {}
      security: []
tags:
  - name: "MAILS"
    description: "Everything related to MAILS"
